In [3]:
import pandas as pd
import numpy as np

In [8]:
import talib.abstract as ta

In [1]:
max(1,2)

2

In [2]:
max(-1.4, 12)

12

In [4]:
df = pd.read_csv('bitcoin.csv')
tdf = df.tail(200)

In [5]:
tdf.tail(20)

,Date,Open,High,Low,Close,Volume
36148,2021-10-06 14:00:00,53996.99,54550.00,53750.00,54500.40,4630.424800
36149,2021-10-06 15:00:00,54500.40,55156.97,54250.04,54984.19,4393.701760
36150,2021-10-06 16:00:00,54984.20,55054.87,54446.54,54891.32,3430.498620
36151,2021-10-06 17:00:00,54891.32,54917.90,54517.01,54581.22,2185.694960
36152,2021-10-06 18:00:00,54582.09,55109.67,54446.54,54527.82,2983.472340
36153,2021-10-06 19:00:00,54527.82,55078.01,54483.85,55049.99,2056.358740
36154,2021-10-06 20:00:00,55049.99,55386.86,54812.00,54918.24,2562.022010
36155,2021-10-06 21:00:00,54918.24,55273.83,54880.05,55075.37,1617.265880
36156,2021-10-06 22:00:00,55075.38,55280.00,54893.02,55144.72,1516.958190
36157,2021-10-06 23:00:00,55144.72,55750.00,55119.08,55315.00,2887.609264
36158,2021-10-07 00:00:00,55315.00,55332.31,54500.00,54794.88,3291.494880
36159,2021-10-07 01:00:00,54794.88,54909.19,54112.00,54787.30,2806.591760
36160,2021-10-07 02:00:00,54787.30,55230.60,54680.92,55075.56,1938.382900
36161,2021-10-07 03:00:00,55075.57,55215.67,54730.86,54810.94,1540.734810
36162,2021-10-07 04:00:00,54810.93,55237.04,54756.06,55073.20,1450.003900
36163,2021-10-07 05:00:00,55073.20,55073.21,54545.07,54735.76,2251.122020
36164,2021-10-07 06:00:00,54735.77,54968.06,54375.83,54534.16,1783.004260
36165,2021-10-07 07:00:00,54534.16,54793.26,54235.33,54755.92,4163.431360
36166,2021-10-07 08:00:00,54755.91,54778.91,54400.00,54538.30,2049.382180
36167,2021-10-07 09:00:00,54538.31,54547.30,53786.13,53995.50,2739.153610

In [20]:
low = tdf.iloc[-20:]

In [21]:
low

,date,open,high,low,close,volume,atr
36148,2021-10-06 14:00:00,53996.99,54550.00,53750.00,54500.40,4630.424800,767.705262
36149,2021-10-06 15:00:00,54500.40,55156.97,54250.04,54984.19,4393.701760,777.649886
36150,2021-10-06 16:00:00,54984.20,55054.87,54446.54,54891.32,3430.498620,765.555609
36151,2021-10-06 17:00:00,54891.32,54917.90,54517.01,54581.22,2185.694960,739.508065
36152,2021-10-06 18:00:00,54582.09,55109.67,54446.54,54527.82,2983.472340,734.052489
36153,2021-10-06 19:00:00,54527.82,55078.01,54483.85,55049.99,2056.358740,724.060168
36154,2021-10-06 20:00:00,55049.99,55386.86,54812.00,54918.24,2562.022010,713.403014
36155,2021-10-06 21:00:00,54918.24,55273.83,54880.05,55075.37,1617.265880,690.572798
36156,2021-10-06 22:00:00,55075.38,55280.00,54893.02,55144.72,1516.958190,668.887598
36157,2021-10-06 23:00:00,55144.72,55750.00,55119.08,55315.00,2887.609264,666.175627
36158,2021-10-07 00:00:00,55315.00,55332.31,54500.00,54794.88,3291.494880,678.042368
36159,2021-10-07 01:00:00,54794.88,54909.19,54112.00,54787.30,2806.591760,686.552913
36160,2021-10-07 02:00:00,54787.30,55230.60,54680.92,55075.56,1938.382900,676.776277
36161,2021-10-07 03:00:00,55075.57,55215.67,54730.86,54810.94,1540.734810,663.064400
36162,2021-10-07 04:00:00,54810.93,55237.04,54756.06,55073.20,1450.003900,650.058371
36163,2021-10-07 05:00:00,55073.20,55073.21,54545.07,54735.76,2251.122020,641.349916
36164,2021-10-07 06:00:00,54735.77,54968.06,54375.83,54534.16,1783.004260,637.841351
36165,2021-10-07 07:00:00,54534.16,54793.26,54235.33,54755.92,4163.431360,632.133397
36166,2021-10-07 08:00:00,54755.91,54778.91,54400.00,54538.30,2049.382180,614.046011
36167,2021-10-07 09:00:00,54538.31,54547.30,53786.13,53995.50,2739.153610,624.554868

In [11]:
tdf.columns = [col.lower() for col in tdf.columns]

In [12]:
tdf['atr'] = ta.ATR(tdf, timeperiod=14)

C:\Users\xlfin\AppData\Local\Temp\ipykernel_22804\334718746.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tdf['atr'] = ta.ATR(tdf, timeperiod=14)

In [14]:
tdf.tail(20)

,date,open,high,low,close,volume,atr
36148,2021-10-06 14:00:00,53996.99,54550.00,53750.00,54500.40,4630.424800,767.705262
36149,2021-10-06 15:00:00,54500.40,55156.97,54250.04,54984.19,4393.701760,777.649886
36150,2021-10-06 16:00:00,54984.20,55054.87,54446.54,54891.32,3430.498620,765.555609
36151,2021-10-06 17:00:00,54891.32,54917.90,54517.01,54581.22,2185.694960,739.508065
36152,2021-10-06 18:00:00,54582.09,55109.67,54446.54,54527.82,2983.472340,734.052489
36153,2021-10-06 19:00:00,54527.82,55078.01,54483.85,55049.99,2056.358740,724.060168
36154,2021-10-06 20:00:00,55049.99,55386.86,54812.00,54918.24,2562.022010,713.403014
36155,2021-10-06 21:00:00,54918.24,55273.83,54880.05,55075.37,1617.265880,690.572798
36156,2021-10-06 22:00:00,55075.38,55280.00,54893.02,55144.72,1516.958190,668.887598
36157,2021-10-06 23:00:00,55144.72,55750.00,55119.08,55315.00,2887.609264,666.175627
36158,2021-10-07 00:00:00,55315.00,55332.31,54500.00,54794.88,3291.494880,678.042368
36159,2021-10-07 01:00:00,54794.88,54909.19,54112.00,54787.30,2806.591760,686.552913
36160,2021-10-07 02:00:00,54787.30,55230.60,54680.92,55075.56,1938.382900,676.776277
36161,2021-10-07 03:00:00,55075.57,55215.67,54730.86,54810.94,1540.734810,663.064400
36162,2021-10-07 04:00:00,54810.93,55237.04,54756.06,55073.20,1450.003900,650.058371
36163,2021-10-07 05:00:00,55073.20,55073.21,54545.07,54735.76,2251.122020,641.349916
36164,2021-10-07 06:00:00,54735.77,54968.06,54375.83,54534.16,1783.004260,637.841351
36165,2021-10-07 07:00:00,54534.16,54793.26,54235.33,54755.92,4163.431360,632.133397
36166,2021-10-07 08:00:00,54755.91,54778.91,54400.00,54538.30,2049.382180,614.046011
36167,2021-10-07 09:00:00,54538.31,54547.30,53786.13,53995.50,2739.153610,624.554868

In [7]:
low

53750.0

In [24]:
tdf['adx'] = ta.ADX(tdf, 14)

C:\Users\xlfin\AppData\Local\Temp\ipykernel_22804\3643186966.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tdf['adx'] = ta.ADX(tdf, 14)

In [25]:
tdf.tail(100)

,date,open,high,low,close,volume,atr,adx
36068,2021-10-03 06:00:00,47990.13,48057.00,47896.93,47972.99,617.25174,348.788257,23.351321
36069,2021-10-03 07:00:00,47970.15,47970.16,47814.00,47895.99,569.31948,335.231238,22.147425
36070,2021-10-03 08:00:00,47896.00,47983.38,47798.50,47823.99,838.17079,324.491864,20.966444
36071,2021-10-03 09:00:00,47823.98,47869.00,47600.00,47830.09,1489.72226,320.528160,19.842057
36072,2021-10-03 10:00:00,47830.09,47953.20,47730.00,47812.32,625.24084,313.576148,18.461404
...,...,...,...,...,...,...,...,...
36163,2021-10-07 05:00:00,55073.20,55073.21,54545.07,54735.76,2251.12202,641.349916,51.158083
36164,2021-10-07 06:00:00,54735.77,54968.06,54375.83,54534.16,1783.00426,637.841351,49.709936
36165,2021-10-07 07:00:00,54534.16,54793.26,54235.33,54755.92,4163.43136,632.133397,48.013565
36166,2021-10-07 08:00:00,54755.91,54778.91,54400.00,54538.30,2049.38218,614.046011,46.438364
36167,2021-10-07 09:00:00,54538.31,54547.30,53786.13,53995.50,2739.15361,624.554868,43.535297