In [2]:
import pandas as pd

# 创建一个简单的DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

# 应用函数于每一列，计算列的总和
column_sums = df.apply(lambda column: column.sum())
print(column_sums)

A     6
B    15
C    24
dtype: int64

In [11]:
type(column_sums)

pandas.core.series.Series

In [2]:
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [18]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [37]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [31]:
df = df.reset_index(drop=True)
df.index

RangeIndex(start=0, stop=3, step=1)

In [3]:
df1 = pd.DataFrame([[4, 9]] * 23, columns=['A', 'B'])

In [4]:
df1

    A  B
0   4  9
1   4  9
2   4  9
3   4  9
4   4  9
5   4  9
6   4  9
7   4  9
8   4  9
9   4  9
10  4  9
11  4  9
12  4  9
13  4  9
14  4  9
15  4  9
16  4  9
17  4  9
18  4  9
19  4  9
20  4  9
21  4  9
22  4  9

In [6]:
df1.index

RangeIndex(start=0, stop=23, step=1)

In [61]:
rs = df1.apply(lambda row: df1.iloc[4:row.name+1,]['B'].sum(), axis=1)
rs

0       0
1       0
2       0
3       0
4       9
5      18
6      27
7      36
8      45
9      54
10     63
11     72
12     81
13     90
14     99
15    108
16    117
17    126
18    135
19    144
20    153
21    162
22    171
dtype: int64

In [15]:
df1.apply(lambda row: df1.iloc[row['A']:row.name+1]['B'].sum(), axis= 1)

0       0
1       0
2       0
3       0
4       9
5      18
6      27
7      36
8      45
9      54
10     63
11     72
12     81
13     90
14     99
15    108
16    117
17    126
18    135
19    144
20    153
21    162
22    171
dtype: int64