In [1]:
import pandas as pd

In [2]:
import numpy as np
from scipy.signal import argrelmax, argrelmin

In [3]:
tdf = pd.read_csv('bitcoin.csv').tail(100)
tdf.columns = [col.lower() for col in tdf.columns]
tdf

                      date      open      high       low     close      volume
36068  2021-10-03 06:00:00  47990.13  48057.00  47896.93  47972.99   617.25174
36069  2021-10-03 07:00:00  47970.15  47970.16  47814.00  47895.99   569.31948
36070  2021-10-03 08:00:00  47896.00  47983.38  47798.50  47823.99   838.17079
36071  2021-10-03 09:00:00  47823.98  47869.00  47600.00  47830.09  1489.72226
36072  2021-10-03 10:00:00  47830.09  47953.20  47730.00  47812.32   625.24084
...                    ...       ...       ...       ...       ...         ...
36163  2021-10-07 05:00:00  55073.20  55073.21  54545.07  54735.76  2251.12202
36164  2021-10-07 06:00:00  54735.77  54968.06  54375.83  54534.16  1783.00426
36165  2021-10-07 07:00:00  54534.16  54793.26  54235.33  54755.92  4163.43136
36166  2021-10-07 08:00:00  54755.91  54778.91  54400.00  54538.30  2049.38218
36167  2021-10-07 09:00:00  54538.31  54547.30  53786.13  53995.50  2739.15361

[100 rows x 6 columns]

In [4]:
tdf.head(20)

                      date      open      high       low     close      volume
36068  2021-10-03 06:00:00  47990.13  48057.00  47896.93  47972.99   617.25174
36069  2021-10-03 07:00:00  47970.15  47970.16  47814.00  47895.99   569.31948
36070  2021-10-03 08:00:00  47896.00  47983.38  47798.50  47823.99   838.17079
36071  2021-10-03 09:00:00  47823.98  47869.00  47600.00  47830.09  1489.72226
36072  2021-10-03 10:00:00  47830.09  47953.20  47730.00  47812.32   625.24084
36073  2021-10-03 11:00:00  47812.32  48048.00  47778.05  47974.86   972.55548
36074  2021-10-03 12:00:00  47974.86  48090.00  47808.14  47964.43   804.97466
36075  2021-10-03 13:00:00  47964.44  48150.00  47841.00  48052.50  1147.51808
36076  2021-10-03 14:00:00  48052.50  48105.60  47892.99  47965.64   997.50451
36077  2021-10-03 15:00:00  47965.64  48025.31  47799.18  47879.82  1251.80495
36078  2021-10-03 16:00:00  47879.81  48067.69  47821.96  48034.99   937.24598
36079  2021-10-03 17:00:00  48034.99  49228.08  47943.09  48910.24  4172.68238
36080  2021-10-03 18:00:00  48910.23  49176.32  48541.33  48822.03  2520.10677
36081  2021-10-03 19:00:00  48822.03  48960.98  48725.00  48774.76   977.20419
36082  2021-10-03 20:00:00  48774.76  48837.88  48400.59  48425.02  1312.92032
36083  2021-10-03 21:00:00  48425.02  48455.11  47601.89  47758.21  2613.26754
36084  2021-10-03 22:00:00  47758.20  48200.00  47700.00  47984.94  1346.84410
36085  2021-10-03 23:00:00  47988.23  48320.00  47874.00  48200.01  1033.16133
36086  2021-10-04 00:00:00  48200.01  48280.71  47840.00  47860.89  1593.37284
36087  2021-10-04 01:00:00  47860.88  48181.91  47714.27  47810.39  1319.95616

In [5]:
tdf.tail(10)

                      date      open      high       low     close      volume
36158  2021-10-07 00:00:00  55315.00  55332.31  54500.00  54794.88  3291.49488
36159  2021-10-07 01:00:00  54794.88  54909.19  54112.00  54787.30  2806.59176
36160  2021-10-07 02:00:00  54787.30  55230.60  54680.92  55075.56  1938.38290
36161  2021-10-07 03:00:00  55075.57  55215.67  54730.86  54810.94  1540.73481
36162  2021-10-07 04:00:00  54810.93  55237.04  54756.06  55073.20  1450.00390
36163  2021-10-07 05:00:00  55073.20  55073.21  54545.07  54735.76  2251.12202
36164  2021-10-07 06:00:00  54735.77  54968.06  54375.83  54534.16  1783.00426
36165  2021-10-07 07:00:00  54534.16  54793.26  54235.33  54755.92  4163.43136
36166  2021-10-07 08:00:00  54755.91  54778.91  54400.00  54538.30  2049.38218
36167  2021-10-07 09:00:00  54538.31  54547.30  53786.13  53995.50  2739.15361

In [6]:
high_idx = argrelmax(tdf['high'].values, order= 2)[0]

In [7]:
arr = np.array((14, 21, 37, 22, 30, 55, 53, 71, 52, 31, 21, 10, 4, 9, 11, 41, 58, 66, 73, 91, 100, 111))

In [8]:
rs = argrelmax(arr, order=2)

In [9]:
rs

(array([2, 7], dtype=int64),)

In [10]:

tdf

                      date      open      high       low     close      volume
36068  2021-10-03 06:00:00  47990.13  48057.00  47896.93  47972.99   617.25174
36069  2021-10-03 07:00:00  47970.15  47970.16  47814.00  47895.99   569.31948
36070  2021-10-03 08:00:00  47896.00  47983.38  47798.50  47823.99   838.17079
36071  2021-10-03 09:00:00  47823.98  47869.00  47600.00  47830.09  1489.72226
36072  2021-10-03 10:00:00  47830.09  47953.20  47730.00  47812.32   625.24084
...                    ...       ...       ...       ...       ...         ...
36163  2021-10-07 05:00:00  55073.20  55073.21  54545.07  54735.76  2251.12202
36164  2021-10-07 06:00:00  54735.77  54968.06  54375.83  54534.16  1783.00426
36165  2021-10-07 07:00:00  54534.16  54793.26  54235.33  54755.92  4163.43136
36166  2021-10-07 08:00:00  54755.91  54778.91  54400.00  54538.30  2049.38218
36167  2021-10-07 09:00:00  54538.31  54547.30  53786.13  53995.50  2739.15361

[100 rows x 6 columns]

In [11]:
high_idx = argrelmax(tdf['high'].values, order= 2)[0]

In [12]:
high_idx

array([ 7, 11, 23, 26, 36, 42, 52, 56, 63, 71, 79, 86, 89, 94],
      dtype=int64)

In [13]:

def calc_high_idx(index, high_idx):
    high_idx_v = [np.nan]*len(index)
    start_idx = high_idx[0]
    for i, idx in enumerate(high_idx):
        if i == 0:
            continue
        # tdf.iloc[start_idx:idx, tdf.columns.get_loc('high_idx')]= high_idx[i-1]
        high_idx_v[start_idx: idx] = [high_idx[i-1]]*(idx- start_idx)
        start_idx = idx
    # tdf.iloc[start_idx:, tdf.columns.get_loc('high_idx')] = high_idx[-1]
    high_idx_v[start_idx:] = [high_idx[-1]]*(len(high_idx_v) - start_idx)
    return high_idx_v

In [14]:
arr = np.full(10, np.nan)
arr

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [15]:
arr[0: 2] = 1

In [16]:
type(arr[0])

numpy.float64

In [17]:
def calc_high_idx(index, high_idx):
    high_idx_v = np.full(len(index), 0)

    start_idx = high_idx[0]
    for i, idx in enumerate(high_idx):
        if i == 0:
            continue
        high_idx_v[start_idx: idx] = high_idx[i-1]
        start_idx = idx

    high_idx_v[start_idx:] = high_idx[-1]
    return high_idx_v

In [18]:
rs = calc_high_idx(tdf, high_idx)
rs

array([ 0,  0,  0,  0,  0,  0,  0,  7,  7,  7,  7, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 23, 23, 23, 26, 26, 26, 26, 26, 26, 26, 26,
       26, 26, 36, 36, 36, 36, 36, 36, 42, 42, 42, 42, 42, 42, 42, 42, 42,
       42, 52, 52, 52, 52, 56, 56, 56, 56, 56, 56, 56, 63, 63, 63, 63, 63,
       63, 63, 63, 71, 71, 71, 71, 71, 71, 71, 71, 79, 79, 79, 79, 79, 79,
       79, 86, 86, 86, 89, 89, 89, 89, 89, 94, 94, 94, 94, 94, 94])

In [19]:
rs

array([ 0,  0,  0,  0,  0,  0,  0,  7,  7,  7,  7, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 23, 23, 23, 26, 26, 26, 26, 26, 26, 26, 26,
       26, 26, 36, 36, 36, 36, 36, 36, 42, 42, 42, 42, 42, 42, 42, 42, 42,
       42, 52, 52, 52, 52, 56, 56, 56, 56, 56, 56, 56, 63, 63, 63, 63, 63,
       63, 63, 63, 71, 71, 71, 71, 71, 71, 71, 71, 79, 79, 79, 79, 79, 79,
       79, 86, 86, 86, 89, 89, 89, 89, 89, 94, 94, 94, 94, 94, 94])

In [20]:
tdf['high_idx'] = rs

In [21]:
tdf.head(20)

,date,open,high,low,close,volume,high_idx
36068,2021-10-03 06:00:00,47990.13,48057.00,47896.93,47972.99,617.25174,0
36069,2021-10-03 07:00:00,47970.15,47970.16,47814.00,47895.99,569.31948,0
36070,2021-10-03 08:00:00,47896.00,47983.38,47798.50,47823.99,838.17079,0
36071,2021-10-03 09:00:00,47823.98,47869.00,47600.00,47830.09,1489.72226,0
36072,2021-10-03 10:00:00,47830.09,47953.20,47730.00,47812.32,625.24084,0
36073,2021-10-03 11:00:00,47812.32,48048.00,47778.05,47974.86,972.55548,0
36074,2021-10-03 12:00:00,47974.86,48090.00,47808.14,47964.43,804.97466,0
36075,2021-10-03 13:00:00,47964.44,48150.00,47841.00,48052.50,1147.51808,7
36076,2021-10-03 14:00:00,48052.50,48105.60,47892.99,47965.64,997.50451,7
36077,2021-10-03 15:00:00,47965.64,48025.31,47799.18,47879.82,1251.80495,7
36078,2021-10-03 16:00:00,47879.81,48067.69,47821.96,48034.99,937.24598,7
36079,2021-10-03 17:00:00,48034.99,49228.08,47943.09,48910.24,4172.68238,11
36080,2021-10-03 18:00:00,48910.23,49176.32,48541.33,48822.03,2520.10677,11
36081,2021-10-03 19:00:00,48822.03,48960.98,48725.00,48774.76,977.20419,11
36082,2021-10-03 20:00:00,48774.76,48837.88,48400.59,48425.02,1312.92032,11
36083,2021-10-03 21:00:00,48425.02,48455.11,47601.89,47758.21,2613.26754,11
36084,2021-10-03 22:00:00,47758.20,48200.00,47700.00,47984.94,1346.84410,11
36085,2021-10-03 23:00:00,47988.23,48320.00,47874.00,48200.01,1033.16133,11
36086,2021-10-04 00:00:00,48200.01,48280.71,47840.00,47860.89,1593.37284,11
36087,2021-10-04 01:00:00,47860.88,48181.91,47714.27,47810.39,1319.95616,11

In [22]:
tdf.tail(30)

,date,open,high,low,close,volume,high_idx
36138,2021-10-06 04:00:00,51512.13,51593.52,51236.70,51325.83,1788.572970,63
36139,2021-10-06 05:00:00,51325.82,51828.00,51200.56,51512.37,3845.981640,71
36140,2021-10-06 06:00:00,51516.11,51736.11,51450.85,51509.98,1795.945490,71
36141,2021-10-06 07:00:00,51509.97,51575.10,51088.00,51449.99,2514.708150,71
36142,2021-10-06 08:00:00,51450.00,51500.00,50420.00,50693.51,4693.989210,71
36143,2021-10-06 09:00:00,50695.74,50822.00,50382.41,50700.00,3309.284380,71
36144,2021-10-06 10:00:00,50700.00,51478.00,50619.10,51160.35,3675.566410,71
36145,2021-10-06 11:00:00,51160.35,51490.00,51091.30,51306.56,2864.515720,71
36146,2021-10-06 12:00:00,51306.57,52829.00,51259.84,52741.68,7188.980390,71
36147,2021-10-06 13:00:00,52741.68,55555.00,52610.20,53997.00,13067.382057,79
36148,2021-10-06 14:00:00,53996.99,54550.00,53750.00,54500.40,4630.424800,79
36149,2021-10-06 15:00:00,54500.40,55156.97,54250.04,54984.19,4393.701760,79
36150,2021-10-06 16:00:00,54984.20,55054.87,54446.54,54891.32,3430.498620,79
36151,2021-10-06 17:00:00,54891.32,54917.90,54517.01,54581.22,2185.694960,79
36152,2021-10-06 18:00:00,54582.09,55109.67,54446.54,54527.82,2983.472340,79
36153,2021-10-06 19:00:00,54527.82,55078.01,54483.85,55049.99,2056.358740,79
36154,2021-10-06 20:00:00,55049.99,55386.86,54812.00,54918.24,2562.022010,86
36155,2021-10-06 21:00:00,54918.24,55273.83,54880.05,55075.37,1617.265880,86
36156,2021-10-06 22:00:00,55075.38,55280.00,54893.02,55144.72,1516.958190,86
36157,2021-10-06 23:00:00,55144.72,55750.00,55119.08,55315.00,2887.609264,89
36158,2021-10-07 00:00:00,55315.00,55332.31,54500.00,54794.88,3291.494880,89
36159,2021-10-07 01:00:00,54794.88,54909.19,54112.00,54787.30,2806.591760,89
36160,2021-10-07 02:00:00,54787.30,55230.60,54680.92,55075.56,1938.382900,89
36161,2021-10-07 03:00:00,55075.57,55215.67,54730.86,54810.94,1540.734810,89
36162,2021-10-07 04:00:00,54810.93,55237.04,54756.06,55073.20,1450.003900,94
36163,2021-10-07 05:00:00,55073.20,55073.21,54545.07,54735.76,2251.122020,94
36164,2021-10-07 06:00:00,54735.77,54968.06,54375.83,54534.16,1783.004260,94
36165,2021-10-07 07:00:00,54534.16,54793.26,54235.33,54755.92,4163.431360,94
36166,2021-10-07 08:00:00,54755.91,54778.91,54400.00,54538.30,2049.382180,94
36167,2021-10-07 09:00:00,54538.31,54547.30,53786.13,53995.50,2739.153610,94

In [23]:
tdf['test'] = np.nan

In [24]:
tdf

,date,open,high,low,close,volume,high_idx,test
36068,2021-10-03 06:00:00,47990.13,48057.00,47896.93,47972.99,617.25174,0,NaN
36069,2021-10-03 07:00:00,47970.15,47970.16,47814.00,47895.99,569.31948,0,NaN
36070,2021-10-03 08:00:00,47896.00,47983.38,47798.50,47823.99,838.17079,0,NaN
36071,2021-10-03 09:00:00,47823.98,47869.00,47600.00,47830.09,1489.72226,0,NaN
36072,2021-10-03 10:00:00,47830.09,47953.20,47730.00,47812.32,625.24084,0,NaN
...,...,...,...,...,...,...,...,...
36163,2021-10-07 05:00:00,55073.20,55073.21,54545.07,54735.76,2251.12202,94,NaN
36164,2021-10-07 06:00:00,54735.77,54968.06,54375.83,54534.16,1783.00426,94,NaN
36165,2021-10-07 07:00:00,54534.16,54793.26,54235.33,54755.92,4163.43136,94,NaN
36166,2021-10-07 08:00:00,54755.91,54778.91,54400.00,54538.30,2049.38218,94,NaN
36167,2021-10-07 09:00:00,54538.31,54547.30,53786.13,53995.50,2739.15361,94,NaN

In [30]:
def assign_idx(df: pd.DataFrame, idx_arr, col: str) -> [float]:
    idx_v = np.full(len(df), 0)
    start_idx = idx_arr[0]
    print(f'{col}_idx_arr: {idx_arr}')
    for i, idx in enumerate(idx_arr):
        if i == 0:
            continue
        print(f'赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: {df.iloc[idx_arr[i-1], df.columns.get_loc(col)]}')
        idx_v[start_idx: idx] = df.iloc[idx_arr[i-1], df.columns.get_loc(col)]
        start_idx = idx
    idx_v[start_idx:] = df.iloc[idx_arr[-1], df.columns.get_loc(col)]
    return idx_v
    
def get_range(dataframe: pd.DataFrame):
    df = dataframe.copy()
    if 'range_top' not in df.columns:
        df['range_top'] = np.nan
    if 'range_bottom' not in df.columns:
        df['range_bottom'] = np.nan
    high_idx = argrelmax(df['high'].values, order= 2)[0]
    low_idx = argrelmin(df['low'].values, order= 2)[0]
    # assign idx_v to dataframe
    df['range_top'] = assign_idx(df, high_idx, 'high')
    df['range_bottom'] = assign_idx(df, low_idx, 'low')
    return df[['range_top', 'range_bottom']]

In [31]:
rs = get_range(tdf)

high_idx_arr: [ 7 11 23 26 36 42 52 56 63 71 79 86 89 94]
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 48150.0
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 49228.08
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 47865.51
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 47962.51
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 49536.12
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 49799.0
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 50350.0
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 50388.0
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 51886.3
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 51828.0
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 55555.0
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 55386.86
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 55750.0
low_idx_arr: [ 3  9 15 22 26 29 33 39 56 67 75 91]
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 47600.0
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 47799.18
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 47601.89
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 47234.21
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 47471.5
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 47352.77
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 46891.0
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 48556.09
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 49575.94
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 50917.73
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 50382.41

In [34]:
tdf[['range_top', 'range_bottom']] = rs

In [37]:
tdf.head(31)

,date,open,high,low,close,volume,high_idx,test,range_top,range_bottom
36068,2021-10-03 06:00:00,47990.13,48057.00,47896.93,47972.99,617.25174,0,NaN,0,0
36069,2021-10-03 07:00:00,47970.15,47970.16,47814.00,47895.99,569.31948,0,NaN,0,0
36070,2021-10-03 08:00:00,47896.00,47983.38,47798.50,47823.99,838.17079,0,NaN,0,0
36071,2021-10-03 09:00:00,47823.98,47869.00,47600.00,47830.09,1489.72226,0,NaN,0,47600
36072,2021-10-03 10:00:00,47830.09,47953.20,47730.00,47812.32,625.24084,0,NaN,0,47600
36073,2021-10-03 11:00:00,47812.32,48048.00,47778.05,47974.86,972.55548,0,NaN,0,47600
36074,2021-10-03 12:00:00,47974.86,48090.00,47808.14,47964.43,804.97466,0,NaN,0,47600
36075,2021-10-03 13:00:00,47964.44,48150.00,47841.00,48052.50,1147.51808,7,NaN,48150,47600
36076,2021-10-03 14:00:00,48052.50,48105.60,47892.99,47965.64,997.50451,7,NaN,48150,47600
36077,2021-10-03 15:00:00,47965.64,48025.31,47799.18,47879.82,1251.80495,7,NaN,48150,47799
36078,2021-10-03 16:00:00,47879.81,48067.69,47821.96,48034.99,937.24598,7,NaN,48150,47799
36079,2021-10-03 17:00:00,48034.99,49228.08,47943.09,48910.24,4172.68238,11,NaN,49228,47799
36080,2021-10-03 18:00:00,48910.23,49176.32,48541.33,48822.03,2520.10677,11,NaN,49228,47799
36081,2021-10-03 19:00:00,48822.03,48960.98,48725.00,48774.76,977.20419,11,NaN,49228,47799
36082,2021-10-03 20:00:00,48774.76,48837.88,48400.59,48425.02,1312.92032,11,NaN,49228,47799
36083,2021-10-03 21:00:00,48425.02,48455.11,47601.89,47758.21,2613.26754,11,NaN,49228,47601
36084,2021-10-03 22:00:00,47758.20,48200.00,47700.00,47984.94,1346.84410,11,NaN,49228,47601
36085,2021-10-03 23:00:00,47988.23,48320.00,47874.00,48200.01,1033.16133,11,NaN,49228,47601
36086,2021-10-04 00:00:00,48200.01,48280.71,47840.00,47860.89,1593.37284,11,NaN,49228,47601
36087,2021-10-04 01:00:00,47860.88,48181.91,47714.27,47810.39,1319.95616,11,NaN,49228,47601
36088,2021-10-04 02:00:00,47810.40,47883.91,47581.42,47678.16,1353.73032,11,NaN,49228,47601
36089,2021-10-04 03:00:00,47678.16,47798.20,47336.00,47468.79,1617.51466,11,NaN,49228,47601
36090,2021-10-04 04:00:00,47468.79,47844.10,47234.21,47751.99,1829.35088,11,NaN,49228,47234
36091,2021-10-04 05:00:00,47751.98,47865.51,47716.86,47777.05,780.10633,23,NaN,47865,47234
36092,2021-10-04 06:00:00,47777.05,47825.00,47550.77,47710.00,996.35366,23,NaN,47865,47234
36093,2021-10-04 07:00:00,47710.00,47860.63,47589.99,47838.54,972.61596,23,NaN,47865,47234
36094,2021-10-04 08:00:00,47838.54,47962.51,47471.50,47656.49,1357.93377,26,NaN,47962,47471
36095,2021-10-04 09:00:00,47656.49,47759.42,47525.00,47732.22,947.30803,26,NaN,47962,47471
36096,2021-10-04 10:00:00,47732.21,47756.10,47486.15,47626.97,982.44873,26,NaN,47962,47471
36097,2021-10-04 11:00:00,47626.01,47679.36,47352.77,47585.85,1374.40205,26,NaN,47962,47352
36098,2021-10-04 12:00:00,47585.84,47819.43,47448.39,47707.37,1400.46322,26,NaN,47962,47352