In [1]:
import pandas as pd
import numpy as np
import talib.abstract as ta

In [2]:
test = pd.DataFrame({
    'a':[1,2,3,4,5,6,7,np.nan,np.nan,0,1,9,np.nan,10,100,8,23,37,46,55,64,73,82,91]
})

In [3]:
test

        a
0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     NaN
8     NaN
9     0.0
10    1.0
11    9.0
12    NaN
13   10.0
14  100.0
15    8.0
16   23.0
17   37.0
18   46.0
19   55.0
20   64.0
21   73.0
22   82.0
23   91.0

In [4]:
lookback_window = test['a'].rolling(window=7)
print(type(lookback_window))

<class 'pandas.core.window.rolling.Rolling'>

In [5]:
rs1 = (lookback_window == 0)
print(rs1)

False

In [6]:
alist = [0.0, 1.0, 2.0]

In [7]:
0 in alist

True

In [8]:
rs2_0exist = lookback_window.apply(lambda x: 0 in x.values, raw= False)

In [9]:
rs2_0exist

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5     NaN
6     0.0
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
15    NaN
16    NaN
17    NaN
18    NaN
19    0.0
20    0.0
21    0.0
22    0.0
23    0.0
Name: a, dtype: float64

In [10]:
test

        a
0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     NaN
8     NaN
9     0.0
10    1.0
11    9.0
12    NaN
13   10.0
14  100.0
15    8.0
16   23.0
17   37.0
18   46.0
19   55.0
20   64.0
21   73.0
22   82.0
23   91.0

In [11]:
test2 = test.fillna(0)
test2

        a
0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     0.0
8     0.0
9     0.0
10    1.0
11    9.0
12    0.0
13   10.0
14  100.0
15    8.0
16   23.0
17   37.0
18   46.0
19   55.0
20   64.0
21   73.0
22   82.0
23   91.0

In [12]:
rs3 =  test['a'].rolling(window=5).apply(lambda s: 8 in s.values)

In [13]:
rs3

0     NaN
1     NaN
2     NaN
3     NaN
4     0.0
5     0.0
6     0.0
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
15    NaN
16    NaN
17    1.0
18    1.0
19    1.0
20    0.0
21    0.0
22    0.0
23    0.0
Name: a, dtype: float64

In [14]:
8 in [8, 8, 8]

True

In [15]:
test2

        a
0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     0.0
8     0.0
9     0.0
10    1.0
11    9.0
12    0.0
13   10.0
14  100.0
15    8.0
16   23.0
17   37.0
18   46.0
19   55.0
20   64.0
21   73.0
22   82.0
23   91.0

In [16]:
rs10 = test2['a'].rolling(window=7).apply(lambda s: 8 in s, raw= True).fillna(0).astype(int)

In [17]:
rs10

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    0
23    0
Name: a, dtype: int32

In [18]:
rs3

0     NaN
1     NaN
2     NaN
3     NaN
4     0.0
5     0.0
6     0.0
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
15    NaN
16    NaN
17    1.0
18    1.0
19    1.0
20    0.0
21    0.0
22    0.0
23    0.0
Name: a, dtype: float64