In [2]:
import pandas as pd

In [1]:
import numpy as np
import talib.abstract as ta

In [3]:
tdf = pd.read_csv('bitcoin.csv').tail(100)

In [4]:
tdf.columns = [col.lower() for col in tdf.columns]

In [5]:
tdf

                      date      open      high       low     close      volume
36068  2021-10-03 06:00:00  47990.13  48057.00  47896.93  47972.99   617.25174
36069  2021-10-03 07:00:00  47970.15  47970.16  47814.00  47895.99   569.31948
36070  2021-10-03 08:00:00  47896.00  47983.38  47798.50  47823.99   838.17079
36071  2021-10-03 09:00:00  47823.98  47869.00  47600.00  47830.09  1489.72226
36072  2021-10-03 10:00:00  47830.09  47953.20  47730.00  47812.32   625.24084
...                    ...       ...       ...       ...       ...         ...
36163  2021-10-07 05:00:00  55073.20  55073.21  54545.07  54735.76  2251.12202
36164  2021-10-07 06:00:00  54735.77  54968.06  54375.83  54534.16  1783.00426
36165  2021-10-07 07:00:00  54534.16  54793.26  54235.33  54755.92  4163.43136
36166  2021-10-07 08:00:00  54755.91  54778.91  54400.00  54538.30  2049.38218
36167  2021-10-07 09:00:00  54538.31  54547.30  53786.13  53995.50  2739.15361

[100 rows x 6 columns]

In [8]:
tdf['top'] = ta.EMA(tdf.high, 20)
tdf['bottom'] = ta.EMA(tdf.low, 20)

In [9]:
tdf

                      date      open  ...           top        bottom
36068  2021-10-03 06:00:00  47990.13  ...           NaN           NaN
36069  2021-10-03 07:00:00  47970.15  ...           NaN           NaN
36070  2021-10-03 08:00:00  47896.00  ...           NaN           NaN
36071  2021-10-03 09:00:00  47823.98  ...           NaN           NaN
36072  2021-10-03 10:00:00  47830.09  ...           NaN           NaN
...                    ...       ...  ...           ...           ...
36163  2021-10-07 05:00:00  55073.20  ...  54501.830853  53865.646069
36164  2021-10-07 06:00:00  54735.77  ...  54546.233629  53914.235015
36165  2021-10-07 07:00:00  54534.16  ...  54569.759950  53944.815489
36166  2021-10-07 08:00:00  54755.91  ...  54589.679002  53988.166395
36167  2021-10-07 09:00:00  54538.31  ...  54585.642907  53968.924834

[100 rows x 8 columns]

In [17]:
tdf['within_range'] = np.where(
    (tdf['close'] < tdf['top']) & (tdf['close'] > tdf['bottom']), True, False
)

In [18]:
tdf

                      date      open  ...        bottom  within_range
36068  2021-10-03 06:00:00  47990.13  ...           NaN         False
36069  2021-10-03 07:00:00  47970.15  ...           NaN         False
36070  2021-10-03 08:00:00  47896.00  ...           NaN         False
36071  2021-10-03 09:00:00  47823.98  ...           NaN         False
36072  2021-10-03 10:00:00  47830.09  ...           NaN         False
...                    ...       ...  ...           ...           ...
36163  2021-10-07 05:00:00  55073.20  ...  53865.646069         False
36164  2021-10-07 06:00:00  54735.77  ...  53914.235015          True
36165  2021-10-07 07:00:00  54534.16  ...  53944.815489         False
36166  2021-10-07 08:00:00  54755.91  ...  53988.166395          True
36167  2021-10-07 09:00:00  54538.31  ...  53968.924834          True

[100 rows x 9 columns]