In [2]:
import pandas as pd

In [10]:
import numpy as np
import talib.abstract as ta
from scipy import stats

In [3]:
tdf = pd.read_csv('bitcoin.csv').tail(100)

In [4]:
tdf.columns = [col.lower() for col in tdf.columns]
tdf

                      date      open      high       low     close      volume
36068  2021-10-03 06:00:00  47990.13  48057.00  47896.93  47972.99   617.25174
36069  2021-10-03 07:00:00  47970.15  47970.16  47814.00  47895.99   569.31948
36070  2021-10-03 08:00:00  47896.00  47983.38  47798.50  47823.99   838.17079
36071  2021-10-03 09:00:00  47823.98  47869.00  47600.00  47830.09  1489.72226
36072  2021-10-03 10:00:00  47830.09  47953.20  47730.00  47812.32   625.24084
...                    ...       ...       ...       ...       ...         ...
36163  2021-10-07 05:00:00  55073.20  55073.21  54545.07  54735.76  2251.12202
36164  2021-10-07 06:00:00  54735.77  54968.06  54375.83  54534.16  1783.00426
36165  2021-10-07 07:00:00  54534.16  54793.26  54235.33  54755.92  4163.43136
36166  2021-10-07 08:00:00  54755.91  54778.91  54400.00  54538.30  2049.38218
36167  2021-10-07 09:00:00  54538.31  54547.30  53786.13  53995.50  2739.15361

[100 rows x 6 columns]

In [5]:
tdf['ma20'] = ta.EMA(tdf['close'], 20)

In [6]:
tdf.tail(10)

                      date      open  ...      volume          ma20
36158  2021-10-07 00:00:00  55315.00  ...  3291.49488  53764.192355
36159  2021-10-07 01:00:00  54794.88  ...  2806.59176  53861.631178
36160  2021-10-07 02:00:00  54787.30  ...  1938.38290  53977.243447
36161  2021-10-07 03:00:00  55075.57  ...  1540.73481  54056.643119
36162  2021-10-07 04:00:00  54810.93  ...  1450.00390  54153.458060
36163  2021-10-07 05:00:00  55073.20  ...  2251.12202  54208.915388
36164  2021-10-07 06:00:00  54735.77  ...  1783.00426  54239.891065
36165  2021-10-07 07:00:00  54534.16  ...  4163.43136  54289.036678
36166  2021-10-07 08:00:00  54755.91  ...  2049.38218  54312.776042
36167  2021-10-07 09:00:00  54538.31  ...  2739.15361  54282.559276

[10 rows x 7 columns]

In [7]:
def calc_slope(x):
    return np.polyfit(range(5), x, 1)[0]

In [8]:
tdf['slope'] = tdf['ma20'].rolling(5).apply(calc_slope, raw= True)

In [9]:
tdf

                      date      open  ...          ma20      slope
36068  2021-10-03 06:00:00  47990.13  ...           NaN        NaN
36069  2021-10-03 07:00:00  47970.15  ...           NaN        NaN
36070  2021-10-03 08:00:00  47896.00  ...           NaN        NaN
36071  2021-10-03 09:00:00  47823.98  ...           NaN        NaN
36072  2021-10-03 10:00:00  47830.09  ...           NaN        NaN
...                    ...       ...  ...           ...        ...
36163  2021-10-07 05:00:00  55073.20  ...  54208.915388  87.078303
36164  2021-10-07 06:00:00  54735.77  ...  54239.891065  67.756750
36165  2021-10-07 07:00:00  54534.16  ...  54289.036678  55.122012
36166  2021-10-07 08:00:00  54755.91  ...  54312.776042  39.875725
36167  2021-10-07 09:00:00  54538.31  ...  54282.559276  22.017275

[100 rows x 8 columns]

In [12]:
tdf['slope2'] = tdf['ma20'].rolling(5).apply(lambda x: stats.linregress(range(5), x.values )[0])

In [13]:
tdf

                      date      open  ...      slope     slope2
36068  2021-10-03 06:00:00  47990.13  ...        NaN        NaN
36069  2021-10-03 07:00:00  47970.15  ...        NaN        NaN
36070  2021-10-03 08:00:00  47896.00  ...        NaN        NaN
36071  2021-10-03 09:00:00  47823.98  ...        NaN        NaN
36072  2021-10-03 10:00:00  47830.09  ...        NaN        NaN
...                    ...       ...  ...        ...        ...
36163  2021-10-07 05:00:00  55073.20  ...  87.078303  87.078303
36164  2021-10-07 06:00:00  54735.77  ...  67.756750  67.756750
36165  2021-10-07 07:00:00  54534.16  ...  55.122012  55.122012
36166  2021-10-07 08:00:00  54755.91  ...  39.875725  39.875725
36167  2021-10-07 09:00:00  54538.31  ...  22.017275  22.017275

[100 rows x 9 columns]

In [14]:
tdf['slope3'] = ta.LINEARREG_SLOPE(tdf['ma20'], timeperiod=5)

In [15]:
tdf

                      date      open      high  ...      slope     slope2     slope3
36068  2021-10-03 06:00:00  47990.13  48057.00  ...        NaN        NaN        NaN
36069  2021-10-03 07:00:00  47970.15  47970.16  ...        NaN        NaN        NaN
36070  2021-10-03 08:00:00  47896.00  47983.38  ...        NaN        NaN        NaN
36071  2021-10-03 09:00:00  47823.98  47869.00  ...        NaN        NaN        NaN
36072  2021-10-03 10:00:00  47830.09  47953.20  ...        NaN        NaN        NaN
...                    ...       ...       ...  ...        ...        ...        ...
36163  2021-10-07 05:00:00  55073.20  55073.21  ...  87.078303  87.078303  87.078303
36164  2021-10-07 06:00:00  54735.77  54968.06  ...  67.756750  67.756750  67.756750
36165  2021-10-07 07:00:00  54534.16  54793.26  ...  55.122012  55.122012  55.122012
36166  2021-10-07 08:00:00  54755.91  54778.91  ...  39.875725  39.875725  39.875725
36167  2021-10-07 09:00:00  54538.31  54547.30  ...  22.017275  22.017275  22.017275

[100 rows x 10 columns]