In [2]:
import pandas as pd
import numpy as np

# 创建一个包含正数和NaN的Series
s = pd.Series([1, 2, np.nan, 4, 5, np.nan, 7])

# 计算50%分位数
median = s.quantile(0.5)
print("Median:", median)

# 计算25%分位数
first_quartile = s.quantile(0.25)
print("First Quartile:", first_quartile)

# 计算75%分位数
third_quartile = s.quantile(0.75)
print("Third Quartile:", third_quartile)

Median: 4.0
First Quartile: 2.0
Third Quartile: 5.0

In [4]:
s2 = pd.Series([1,2,3,4])
print(s2.quantile(0.5))

2.5

In [5]:
print(s2.quantile(0.7))

3.0999999999999996

In [15]:
s3 = pd.Series([-1, -2, np.nan, -4, np.nan,np.nan,np.nan,np.nan,np.nan,])

In [16]:
print(s3.quantile(0.3))

-2.8

In [19]:
print(s3.quantile(0.3, 'midpoint'))
print(s3.quantile(0.3, 'nearest'))
print(s3.quantile(0.3))

-3.0
-2.0
-2.8

In [26]:
import random
s4 = pd.Series([random.randint(1, 100) for _ in range(100)])
print(s4)

0     72
1     34
2     13
3     15
4     98
      ..
95    56
96    44
97    12
98    85
99    21
Length: 100, dtype: int64

In [24]:
deviation = -3
passRegressionFilter = (deviation > s3.quantile(0.3))
print(passRegressionFilter)

False

In [28]:
bull_deviation = 14
print(s4.quantile(0.7))
pass_bull_regfilter = (bull_deviation < s4.quantile(0.7) )
print(pass_bull_regfilter)

70.3
True

In [34]:
from math import nan
s5 = pd.Series([0, -1, nan,-4, nan, -3, 0, 1])
s5

0    0.0
1   -1.0
2    NaN
3   -4.0
4    NaN
5   -3.0
6    0.0
7    1.0
dtype: float64

In [36]:
filter_pos_s5 = s5.mask(s5>0)
filter_pos_s5

0    0.0
1   -1.0
2    NaN
3   -4.0
4    NaN
5   -3.0
6    0.0
7    NaN
dtype: float64

In [43]:
test = filter_pos_s5.mask(filter_pos_s5<=0)
test

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
dtype: float64

In [44]:
rs1 = test.quantile(0.7)
rs1

nan

In [38]:
pos_s5 = s5[s5>0]
pos_s5

7    1.0
dtype: float64

In [45]:
test3 = pd.Series([-1,-2,-3,0, 1,2,3])

In [ ]:
rs = np.where(
    df['deviation'] >0, np.where(
        df['deviation'] > df['bull_quantile'], 0, 1
    ),
    np.where(
        df['deviation'] < df['bear_quantile'], 0, 1
    )
)

In [46]:
df = pd.DataFrame(test3)

In [47]:
df

   0
0 -1
1 -2
2 -3
3  0
4  1
5  2
6  3

In [48]:
df['test_column'] = nan

In [49]:
df

   0  test_column
0 -1          NaN
1 -2          NaN
2 -3          NaN
3  0          NaN
4  1          NaN
5  2          NaN
6  3          NaN

In [54]:
df.columns.dtype

dtype('O')

In [59]:
df['retest_column'] = np.where(
        df.iloc[:,0] < 0, 
        'neg',
        np.where(
            df.iloc[:,0] > 0,
            'pos',
            'zero'
        )
    )

In [58]:
df

   0  test_column retest_column
0 -1          NaN           neg
1 -2          NaN           neg
2 -3          NaN           neg
3  0          NaN          zero
4  1          NaN           pos
5  2          NaN           pos
6  3          NaN           pos

In [61]:
df.iloc[:, 0] > df['test_column']

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [5]:
import numpy as np
import pandas as pd
import timeit  # 导入timeit模块

# 创建一个大的DataFrame进行测试
df = pd.DataFrame({
    'x': np.random.randn(1000000),
    'y': np.random.randn(1000000),
    'z': np.random.randn(1000000)
})

# 定义要测试的两种写法
def test_method_1():
    return np.where((df.x > df.y) | (df.x < df.z), 0, 1)

def test_method_2():
    return np.where(df.x > 0, np.where(df.x > df.y, 0, 1), np.where(df.x < df.z, 0, 1))

# 测试第一种写法
print(timeit.timeit('test_method_1()', globals=globals(), number=10))

# 测试第二种写法
print(timeit.timeit('test_method_2()', globals=globals(), number=10))

0.032649800000001505
0.04389260000004924